### PR TITLE
Revert "support for modifying extension of outputted files"

### PR DESCRIPTION
**Pull request by PiPeep**
This reverts commit 16d61846c5c0f4969345812f2e6acfca681e3501.

As per the discussion in #10 . To my surprise, `git-revert` worked flawlessly. Code passes `grunt test`. Bumped to v0.2.0, as this change is not backwards compatible.

### CODE REVIEW

**Comment by PiPeep** [comment]
I'm trying to close out some old PRs. @dlasky, any chance you can review this?

**Comment by dlasky** [comment]
can you undo the version tick? I'll handle that via npm.

**Comment by PiPeep** [comment]
@dlasky, sure. I'll do it when I get home.

**Comment by dlasky** [comment]
sounds good.

**Comment by PiPeep** [comment]
Done. Thanks!

**Pull request merged**
